stages:
  - build

build:
  stage: build
  only:
    - main
  except:
    - schedules
  script:
    - echo $SSH_PRIVATE_KEY
    - chmod 400 $SSH_PRIVATE_KEY
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ecs-assist-user@106.14.158.113 "cd /var/www/node-backend && git pull git@gitlab.com:yousi/node-backend.git && npm install && npm run build && pm2 restart node-backend"